version: 2
updates:

  # Datatypes crate
  - package-ecosystem: "cargo"
    # Look for `Cargo.toml` and `lock` files in the `root` directory
    directory: "/datatypes"
    # Check the `crates.io` for updates every day (weekdays)
    schedule:
      interval: "daily"

  # Operators crate
  - package-ecosystem: "cargo"
    # Look for `Cargo.toml` and `lock` files in the `root` directory
    directory: "/operators"
    # Check the `crates.io` for updates every day (weekdays)
    schedule:
      interval: "daily"

  # Services crate
    - package-ecosystem: "cargo"
      # Look for `Cargo.toml` and `lock` files in the `root` directory
      directory: "/services"
      # Check the `crates.io` for updates every day (weekdays)
      schedule:
        interval: "daily"
