[postgres]
host = "localhost"
port = 5432
database = "geoengine"
schema = "pg_temp" # we need the right to create new schemata for tests
user = "geoengine"
password = "geoengine"

[operators.gdal_source]
raster_data_root_path = "../operators/test-data/raster" # relative to sub crate directory for tests

[raster.tiling_specification]
    origin_coordinate_x = 0.0
    origin_coordinate_y = 0.0
    tile_shape_pixels_x = 600
    tile_shape_pixels_y = 600

[upload]
path = "test_upload"
